"""Textos de exemplo usados no benchmark de desempenho (issue 18).

Não são lorem ipsum: são textos reais e coerentes em português, para que o
resumo gerado pela LLM seja representativo de um caso de uso real.
"""

SMALL_TEXT = (
    "A energia solar fotovoltaica é uma das formas mais promissoras de geração de "
    "eletricidade a partir de fontes renováveis. Painéis solares convertem a luz do sol "
    "diretamente em eletricidade por meio do efeito fotovoltaico, um fenômeno físico "
    "descoberto no século XIX.\n\n"
    "Nos últimos anos, o custo de produção de painéis solares caiu drasticamente, "
    "tornando essa tecnologia cada vez mais acessível tanto para residências quanto para "
    "grandes usinas. Além da redução de custos, a energia solar contribui para a "
    "diminuição da emissão de gases de efeito estufa, sendo uma alternativa importante "
    "frente às mudanças climáticas.\n\n"
    "Apesar das vantagens, a intermitência da geração solar, que depende da "
    "disponibilidade de luz solar, ainda representa um desafio para a integração em "
    "larga escala às redes elétricas, exigindo investimentos complementares em "
    "armazenamento de energia e em sistemas de distribuição mais flexíveis."
)

MEDIUM_TEXT = (
    "Introdução\n\n"
    "As mudanças climáticas representam um dos maiores desafios enfrentados pela "
    "humanidade no século XXI. O aumento da temperatura média global, observado de "
    "forma consistente nas últimas décadas, está diretamente relacionado ao acúmulo de "
    "gases de efeito estufa na atmosfera, principalmente o dióxido de carbono (CO2), o "
    "metano (CH4) e o óxido nitroso (N2O). Esses gases retêm calor irradiado pela "
    "superfície terrestre, intensificando o chamado efeito estufa natural e provocando "
    "um desequilíbrio no sistema climático do planeta. Embora o efeito estufa seja um "
    "fenômeno natural e essencial para manter temperaturas compatíveis com a vida na "
    "Terra, a intensificação causada pela atividade humana tem gerado consequências "
    "cada vez mais visíveis e preocupantes.\n\n"
    "Causas principais\n\n"
    "A queima de combustíveis fósseis, como carvão, petróleo e gás natural, para "
    "geração de energia e transporte é a principal fonte de emissões antrópicas de "
    "CO2. O desmatamento também contribui significativamente, pois reduz a capacidade "
    "de florestas de absorver carbono da atmosfera, além de liberar o carbono "
    "armazenado na vegetação quando ela é queimada ou removida. A agropecuária, "
    "especialmente a pecuária de grande escala, é uma fonte relevante de metano, "
    "gerado principalmente pela fermentação entérica dos ruminantes. Processos "
    "industriais, gestão inadequada de resíduos sólidos e certas práticas agrícolas "
    "completam o quadro das principais fontes de emissão.\n\n"
    "Efeitos observados\n\n"
    "Entre os efeitos já observados das mudanças climáticas estão o derretimento "
    "acelerado de geleiras e calotas polares, a elevação do nível médio dos oceanos, "
    "a intensificação de eventos climáticos extremos como ondas de calor, secas "
    "prolongadas e tempestades mais intensas, além de alterações nos padrões de chuva "
    "em diversas regiões do mundo. Ecossistemas terrestres e marinhos sofrem pressões "
    "adicionais, com espécies sendo forçadas a migrar para áreas com condições mais "
    "favoráveis ou enfrentando risco elevado de extinção. Recifes de coral, "
    "particularmente sensíveis a variações de temperatura, têm sofrido eventos "
    "recorrentes de branqueamento, comprometendo toda a cadeia alimentar marinha que "
    "deles depende.\n\n"
    "Impactos socioeconômicos\n\n"
    "Os impactos das mudanças climáticas não se restringem ao meio ambiente: eles "
    "afetam diretamente a segurança alimentar, a disponibilidade de água potável, a "
    "saúde pública e a estabilidade econômica de diversas regiões. Populações em "
    "situação de vulnerabilidade social, especialmente em países em desenvolvimento, "
    "tendem a ser as mais afetadas, pois possuem menor capacidade de adaptação e "
    "recursos limitados para lidar com desastres naturais. Fenômenos como migrações "
    "forçadas por questões climáticas já são registrados em diferentes partes do "
    "mundo, configurando o que pesquisadores chamam de refugiados climáticos.\n\n"
    "Estratégias de mitigação\n\n"
    "A mitigação das mudanças climáticas envolve ações voltadas à redução das "
    "emissões de gases de efeito estufa. Isso inclui a transição para fontes de "
    "energia renovável, como solar, eólica e hidrelétrica, o aumento da eficiência "
    "energética em processos industriais e residenciais, a promoção do transporte "
    "público e de veículos elétricos, e a implementação de políticas de "
    "reflorestamento e conservação de florestas nativas. Acordos internacionais, "
    "como o Acordo de Paris, estabelecem metas coletivas para limitar o aumento da "
    "temperatura global, exigindo compromisso e cooperação entre países "
    "desenvolvidos e em desenvolvimento.\n\n"
    "Estratégias de adaptação\n\n"
    "Além da mitigação, é necessário investir em estratégias de adaptação, que "
    "visam reduzir a vulnerabilidade de comunidades e ecossistemas aos efeitos já "
    "inevitáveis das mudanças climáticas. Isso envolve o desenvolvimento de "
    "infraestrutura resiliente, sistemas de alerta antecipado para eventos extremos, "
    "manejo sustentável de recursos hídricos, e o desenvolvimento de variedades "
    "agrícolas mais resistentes a secas e a variações de temperatura. A adaptação é "
    "particularmente importante para regiões costeiras, que enfrentam risco crescente "
    "de inundação devido à elevação do nível do mar.\n\n"
    "Conclusão\n\n"
    "Enfrentar as mudanças climáticas exige uma combinação de esforços globais e "
    "locais, envolvendo governos, setor privado, sociedade civil e indivíduos. A "
    "urgência do problema demanda ações coordenadas de mitigação e adaptação, "
    "apoiadas por avanços científicos e tecnológicos, além de mudanças significativas "
    "em padrões de produção e consumo. O sucesso dessas iniciativas dependerá da "
    "capacidade coletiva de equilibrar desenvolvimento econômico com sustentabilidade "
    "ambiental, garantindo condições de vida dignas para as gerações presentes e "
    "futuras."
)
